#!/bin/sh -e
keytool -genkey -keyalg RSA -alias test1.example.com -keystore keys.jks -storepass password -validity 3650 -keysize 2048
keytool -genkey -keyalg RSA -alias test2.example.com -keystore keys.jks -storepass password -validity 3650 -keysize 2048
